name       : highlight
version    : '3.52'
release    : 8
source     :
    - https://gitlab.com/saalen/highlight/-/archive/v3.52/highlight-v3.52.tar.gz : 08c50c6e9fe2a09452c64adc3af386c9ae7ccb4abc1fc91af64e1aad40af06f6
license    : GPL-3.0
component  : programming.tools
summary    : Convert source code to formatted text with syntax highlighting
description: |
    Highlight converts source code to HTML, XHTML, RTF, LaTex, TeX, SVG, BBCode and terminal escape sequences with coloured syntax highlighting. Language definitions and colour themes are customizable.
builddeps  :
    - pkgconfig(lua-5.3)
    - libboost-devel
build      : |
    %make
install    : |
    %make_install

    # remove necessary documentation files
    rm -r $installdir/usr/share/doc
