name       : highlight
version    : '4.7'
release    : 14
source     :
    - https://gitlab.com/saalen/highlight/-/archive/v4.7/highlight-v4.7.tar.gz : 4792ae419310f5f5e0895666718e15b349c26ce21cd6a41fd28c427987bb4b92
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Convert source code to formatted text with syntax highlighting
description: |
    Highlight converts source code to HTML, XHTML, RTF, LaTex, TeX, SVG, BBCode and terminal escape sequences with coloured syntax highlighting. Language definitions and colour themes are customizable.
builddeps  :
    - pkgconfig(lua-5.3)
    - libboost-devel
build      : |
    %make
install    : |
    %make_install

    # remove necessary documentation files
    rm -r $installdir/usr/share/doc
